#!/usr/bin/env bash
# install nginx server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
