#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get install -y nginx
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
