#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get install -y nginx
sudo chown -R $USER:$USER /var/www
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
