#!/usr/bin/env bash
# configure new server

# update and install nginx
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

ERROR="\\\terror_page 404 /404.html;"
sudo sed -i '/:80 default_server;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i "/:80 default_server;/a $ERROR" /etc/nginx/sites-available/default
sudo sed -i '/:80 default_server;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
