#!/usr/bin/env bash
#fizzbuzz challenge

I=1

while [ $I -le 100 ]
do
    if [ $((I%15)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((I%3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((I%5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$I"
    fi

    I=$((I + 1))
done
