#!/usr/bin/env bash
# print bad luck for 4th iter good luck for 8th best school for other

I=1

while [ $I -le 10 ]
do
    if [ $I -eq 4 ]; then
        echo "bad luck"
    elif [ $I -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    I=$((I+1))
done
