#!/usr/bin/env bash
#print number, from 4th, 9th, 17th print bad luck from china/japan/italy

I=1

while [ $I -le 20 ]
do
    echo "$I"
    case $I in
        4)
        echo "bad luck from China"
        ;;
        9)
        echo "bad luck from Japan"
        ;;
        17)
        echo "bad luck from Italy"
    esac
    I=$((I+1))
done
